blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooCodeInc/Bitx/discussions/categories/feature-requests
      about: Share and vote on feature requests for Bitx
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline-bitx&ssr=false#review-details
      about: Enjoying Bitx? Leave a review here!
